# Generated by Django 5.0 on 2024-01-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sponsor_link',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
