# Generated by Django 5.0 on 2024-01-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomadApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image10_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image1_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image4_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image5_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image6_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image7_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image8_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image9_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_image_description',
        ),
    ]
