# Generated by Django 5.0 on 2024-04-20 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomadApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image10_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image1_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image4_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image5_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image6_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image7_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image8_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image9_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_image_description',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='nomadApp.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nomadApp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
